data:
  train_dir: "/mnt/Speckle/Prepared/5x5x5"
  intervals: # Numbers of frames to use for temporal context
    - 1
    - 5
    - 7
  val_dir:    # List of validation data directories
    noise: "../ValidSet/noise"
    refer: "../ValidSet/refer"

model:
  in_channels: 1
  out_channels: 1

training:
  device: "cuda"  # or "cpu"
  batch_size: 8
  num_workers: 2
  learning_rate: 0.001
  epochs: 1
  save_interval: 1
  val_interval: 100
  checkpoint_dir: "checkpoints"
  parallel_train: false
  scheduler:
    type: "reduce_on_plateau"  # Adaptive learning rate based on loss plateau
    mode: "min"  # Monitor loss (minimize)
    factor: 0.5  # Multiply lr by this factor when plateauing
    patience: 5  # Number of epochs to wait before reducing lr
    min_lr: 0.00001  # Minimum learning rate
    threshold: 0.0001  # Minimum change in monitored value to qualify as an improvement
    cooldown: 2  # Number of epochs to wait before resuming normal operation after lr has been reduced

loss:
  alpha: 0.5  # Weight for spatial-temporal loss
  tv_weight: 1.0  # Weight for gradient loss

wandb:
  project: "speckle-denoising"  # Your project name
  name: "0"  # Optional: specific run name
  tags: []  # Optional: list of tags for this run
  notes: ""  # Optional: notes about this run
  log_interval: 10  # Log metrics every N batches 
